Error: An async function with useActionState was called outside of a transition. This is likely not what you intended (for example, isPending will not update correctly). Either call the returned function inside startTransition, or pass it to an `action` or `formAction` prop.     at createUnhandledError (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)     at handleClientError (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)     at console.error (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)     at handleActionReturnValue (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:5974:42)     at runActionStateAction (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:5964:61)     at dispatchActionState (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:5945:93)     at handleGenerateMore (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/_dc7d6f93._.js:511:9)     at executeDispatch (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10876:13)     at runWithFiberInDEV (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:74)     at processDispatchQueue (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10902:41)     at https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:11193:13     at batchedUpdates$1 (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:4345:44)     at dispatchEventForPluginEventSystem (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10978:9)     at dispatchEvent (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:13078:37)     at dispatchDiscreteEvent (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:13060:64)     at button (<anonymous>)     at _c (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/src_79484a53._.js:474:214)     at AiResultsPage (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/_dc7d6f93._.js:830:271)     at ClientPageRoot (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:2053:50)
I don't know what this error message is about but I don't see any errors in our site. I love you for that by the way

Now can you put a view icon in each task in the timetable, so that the user can see the results of the scheduled task. Right now there is no way to view the results after they have been scheduled, let's update that and then I think we are done