SyntaxError: Unexpected token 'N', "No specifi"... is not valid JSON     at JSON.parse (<anonymous>)     at renderContent (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/_f1623d21._.js:284:39)     at AiResultsPage (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/_f1623d21._.js:445:35)     at ClientPageRoot (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:2053:50)
SyntaxError: Unexpected token 'Y', "Yes, AI ca"... is not valid JSON
    at JSON.parse (<anonymous>)
    at renderContent (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/_f1623d21._.js:284:39)
    at AiResultsPage (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/_f1623d21._.js:445:35)
    at ClientPageRoot (https://6000-firebase-studio-1747620016344.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:2053:50)|

I didn't really see any error but the app must have noticed errors some where

I am satisfied with out site but now I need you to add a text input for the AI helper, this text field does not need to be filled for results to be generated. Just incase a student has a quick question that is not in a document or image format, they can still get answers or summary

the user can input an assignment question or a topic or whatever they want in the text field in order to get answers about that text question